### ISSUE TITLE
Deployment to CF fails

### ISSUE THREAD

**Issue by kartiklunkad26** [woonsanko/hippo-on-spring-boot#1] opened 2017-01-13 00:07 UTC
When deploying to cloud foundry, the 'cf push' command fails with the below error. 

`ERR Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/EmbeddedServletContainerFactory
2017-01-12T19:00:21.95-0500 [APP/PROC/WEB/0]ERR 	at java.lang.Class.getDeclaredMethods0(Native Method)
2017-01-12T19:00:21.95-0500 [APP/PROC/WEB/0]ERR 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
2017-01-12T19:00:21.95-0500 [APP/PROC/WEB/0]ERR 	at java.lang.Class.getDeclaredMethod(Class.java:2128)
2017-01-12T19:00:21.95-0500 [APP/PROC/WEB/0]ERR 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
2017-01-12T19:00:21.95-0500 [APP/PROC/WEB/0]ERR 	at java.lang.Thread.run(Thread.java:745)
2017-01-12T19:00:21.95-0500 [APP/PROC/WEB/0]ERR Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.EmbeddedServletContainerFactory
2017-01-12T19:00:21.95-0500 [APP/PROC/WEB/0]ERR 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2017-01-12T19:00:21.95-0500 [APP/PROC/WEB/0]ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2017-01-12T19:00:21.95-0500 [APP/PROC/WEB/0]ERR 	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:178)
2017-01-12T19:00:21.95-0500 [APP/PROC/WEB/0]ERR 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
2017-01-12T19:00:21.95-0500 [APP/PROC/WEB/0]ERR 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2017-01-12T19:00:21.95-0500 [APP/PROC/WEB/0]ERR 	... 5 more`

**Comment by woonsanko** [comment] 2017-01-13 01:17
It might have been caused by a lower version of JRE. Could you make sure it is JRE 1.8?
Also, Hippo recommends using Oracle JVM, not OpenJDK. Could you set the env to use Oracle JVM somehow instead?

**Comment by woonsanko** [comment] 2018-05-03 00:01
Closing as it's outdated.

**Closed as completed by woonsanko** 2018-05-03 00:01 UTC
